version: "3"

services:
  mssql:
    image: rohanmohapatra/mssql-server:latest
    container_name: mssql
    restart: always
    ports:
      - 1433:1433
    environment:
      SA_PASSWORD: R0hanM0hapatra
